export function PullRequestsView() {
  return (
    <div style={{ display: 'flex', height: '100%', width: '100%' }}>
      {/* Internal Sidebar for filtering */}
      <div style={{ width: '200px', borderRight: '1px solid var(--surface-border)', padding: '10px' }}>
        <h3>Filters</h3>
        <ul style={{ listStyle: 'none', padding: 0, marginTop: '10px' }}>
          <li><label><input type="checkbox" checked /> Open</label></li>
          <li><label><input type="checkbox" checked /> Closed</label></li>
        </ul>
        <h4 style={{ marginTop: '20px' }}>Repositories</h4>
        <ul style={{ listStyle: 'none', padding: 0, marginTop: '10px' }}>
          <li><label><input type="checkbox" checked /> goddard-ai/cli</label></li>
        </ul>
      </div>

      {/* Main Content Area */}
      <div style={{ flex: 1, padding: '20px', overflowY: 'auto' }}>
        <h2>Pull Requests</h2>
        <p>List of PRs generated by Goddard.</p>
      </div>
    </div>
  );
}
